version: 2.1
executors:
  bt_project:
    docker:
      - image: gcr.io/emily-cloud-build/node:14-base
    working_directory: ~/app
  containerize:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    working_directory: ~/app
jobs:
  build_project:
    executor: bt_project
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}-
            - npm-cache-
      - run:
          name: Build Project
          command: |
            npm ci
            npm run build
            npm prune -- production
            /usr/local/bin/node-prune
      - save_cache:
          paths:
            - /home/circleci/app/node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: /home/circleci/app
          paths:
            - node_modules
            - dist
            - Dockerfile
  test_project:
    executor: bt_project
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}-
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint Project
          command: npm run lint
      - run:
          name: Test Project
          command: npm run test
      - save_cache:
          paths:
            - /home/circle_ci/app/node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
  build_push_latest_image:
    executor: containerize
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Install Podman
          command: |
            echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list
            curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key| sudo apt-key add -
            sudo apt-get update
            sudo apt-get install podman
            sudo chmod 4755 /usr/bin/newgidmap
            sudo chmod 4755 /usr/bin/newuidmap
      - run:
          name: Set Build Tag
          command: |
            if [[ -z "${BUILD_TYPE}" ]]; then
              if [[ "${CIRCLECI_TAG}" ]]; then
            fi
      - run:
          name: Build Container Image
          command: |
            podman build -t "${IMAGE_NAME}:latest" .
      - run:
          name: Push to GCR
          command: |
            echo "${GCR_AUTH}" > "${HOME}/gcr-key.json"
            cat "${HOME}/gcr-key.json" | podman login -u _json_key --password-stdin https://gcr.io
            podman image push botmin:latest gcr.io/shitty-discord-bots/botmin:latest

workflows:
  version: 2
  build_latest_push:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - develop   # only build latest on develop
      - build_push_latest_image:
          context:
            - docker
            - docker-latest
          requires:
            - build_project
  build_test_push:
    jobs:
      - test_project:
          filters:
            branches:
              ignore:
                - main
            tags:
              only:
                - /.*/
      - build_project:
          requires:
            - test_project
      - build_push_latest_image:
          context: docker     # pull environment variables
          requires:
            - build_project
  build_nopush:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - /(?!develop)/ # any branch that isn't "develop"
                - /(?!main)/    # any branch that isn't "main"
