version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: install podman
          command: |
            echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list
            curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key| sudo apt-key add -
            sudo apt-get update
            sudo apt-get install podman buildah
      - run:
          name: build container image
          command: podman build -t botmin:latest .
      - run:
          name: push to GCR
          command: |
            echo "${GCR_AUTH}" > "${HOME}/gcr-key.json"
            cat "${HOME}/gcr-key.json" | podman login -u _json_key --password-stdin https://gcr.io
            podman image push botmin:latest gcr.io/shitty-discord-bots/botmin:latest
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker
