version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install podman
      - run:
          name: build docker image
          command: |
            podman build -t $IMAGE_NAME:latest .
      - run:
          name: push to GCR
          command: |
            echo "${GCR_AUTH}" > "${HOME}/gcr-key.json"
            cat "${HOME}/gcr-key.json" | docker login -u _json_key --password-stdin https://gcr.io
            docker tag "${IMAGE_NAME}:latest" "${GCR_IMAGE_NAME}:latest"
            docker push "${GCR_IMAGE_NAME}:latest"
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker
