version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install podman
      - run:
          name: build docker image
          command: |
            podman build -t $IMAGE_NAME:latest .
      - run:
          name: push to GCR
          command: |
            echo "${GCR_AUTH}" > "${HOME}/gcr-key.json"
            cat "${HOME}/gcr-key.json" | docker login -u _json_key --password-stdin https://gcr.io
            docker tag "${IMAGE_NAME}:latest" "${GCR_IMAGE_NAME}:latest"
            docker push "${GCR_IMAGE_NAME}:latest"
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker
